apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serasa-sheep
  annotations:
    github.com/project-slug: aamuzakii/serasa-sheep
spec:
  type: other
  lifecycle: unknown
  owner: guests
